#!/bin/bash

declare -a subjects=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15)
declare -a data="seed-iv"
declare -a session=2
declare -a num_class=4

#declare -a subjects=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15)

# [1]	[File: run_seed]				[Action: Set BS1:50, BS2:50]
# [2]   [File: solver.py] [module: MFA_LR]		[Action: Set weight_decay=0.005 in SGD -> second line]
# [3]	[File: solver.py] [module: RSDA]  		[Action: Set 0.1 * adv_loss for sessions 1,2,3]
# [4]   [File: solver.py] [module: RSDA] 		[Action: Set weight_decay=0.005 from Adam -> two lines]


for subj in "${subjects[@]}"
do
	for iter in {1..5}; do
		seed=$(($((100*$iter))+123));

		echo "Session:" $session "  Subject: " $subj " Iteration:" $iter 		
		
		python3.8 main.py --dataset $data --target $subj --iteration $iter --gpu_id 0 --num_class $num_class --max_iter1 35 --max_iter2 1000 --seed $seed --lr_a 0.01 --lr_b 0.001 --batch_size 50 --session $session --radius 10.0 --stages 2 --bottleneck_dim 512 --test_interval 50

		#python3.8 main.py --dataset $data --target $subj --iteration $iter --gpu_id 0 --num_class $num_class --max_iter1 4000 --max_iter2 1000 --seed $seed --lr_a 0.01 --lr_b 0.001 --batch_size 50 --session $session --radius 10.0 --stages 2 --bottleneck_dim 512 --test_interval 50
		

		echo ""
		echo ""
	done
done

